server:
  port: 8777

eureka:
  instance:
    hostname: server2
  client:
    registerWithEureka: true
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://server1:8761/eureka/

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/dzcp?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: eureka-server
#mybatis-plus:
#  type-aliases-package: com.example.main.model.entity
#  mapper-locations: classpath:mapper/*.xml
ribbon:
  ConnectTimeout: 500 # 连接超时时长
  ReadTimeout: 2000 # 数据通信超时时长
  MaxAutoRetries: 1 # 当前服务器的重试次数
  MaxAutoRetriesNextServer: 1 # 重试多少次服务
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试 GET PUT DELETE POST
  eureka:
    enabled: true
feign:
  compression:
    request:
      enabled: true
    response:
      useGzipDecoder: true
      enabled: true

logging:
  file:
    path: /data/logs/${spring.application.name}
  config: src/main/resources/logback-spring.xml