server:
  port: 8761
#  servlet:
#    context-path: /base

eureka:
  instance:
    hostname: server1
  client:
    registerWithEureka: true
#    fetchRegistry: false
    serviceUrl:
       defaultZone: http://server2:8777/eureka/           # 集群版
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    # 单机版

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/dzcp?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: eureka-server
#hystrix:
#  metrics:
#    enabled: true
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 500

mybatis-plus:
  type-aliases-package: com.example.main.entity
  mapper-locations: classpath:mapper/*.xml
ribbon:
  ConnectTimeout: 500 # 连接超时时长
  ReadTimeout: 2000 # 数据通信超时时长
  MaxAutoRetries: 1 # 当前服务器的重试次数
  MaxAutoRetriesNextServer: 1 # 重试多少次服务
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试 GET PUT DELETE POST
  eureka:
    enabled: true

## 这个MenuServiceProvider是加了@FeignClient注解的类
MenuServiceProvider:
  ribbon:
    ## 服务提供者的地址，不是服务注册中心的地址
    listOfServers: http://localhost:8765