server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://server2:8777/eureka/,http://server1:8761/eureka/

mybatis-plus:
  type-aliases-package: com.example.servicemenu.entity
  mapper-locations: classpath:mapper/*.xml

spring:
  application:
    name: service-media

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dzcp?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    password: root
